services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks: 
            - enviame

    nginx:
        image: nginx:1.20-alpine
        container_name: nginx
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:8080"
            - "443:443"
        networks: 
            - enviame

    mariadb:
        image: mariadb:10.5.9
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: mysecretpassword
            MYSQL_DATABASE: laravel
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - enviame

    composer:
        image: composer:2
        container_name: composer
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
            - ./src/vendor:/var/www/html/vendor
        depends_on: 
            - php
        entrypoint: ['composer']
        networks:
            - enviame

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php
            - mariadb
        working_dir: /var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        networks:
            - enviame

    adminer:
        image: adminer
        restart: always
        container_name: adminer
        depends_on: 
            - php
            - mariadb
        ports:
            - "8000:8080"
        networks:
            - enviame
        
networks:
    enviame:

volumes:
    dbdata:
